[package]
name = "listo_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.20", features = ["multipart"]}
cookie = "0.18.0"
futures = "0.3.28"
http = "0.2.9"
jsonwebtoken = "9.1.0"
mysql_async = "0.32.2"
rust-argon2 = "2.0.0"
serde = { version = "1.0.189", features = ["derive"] }
tokio = { version = "1.33.0", features = ["full"] }
tower = "0.4.13"
